In [2]:
import numpy as np

In [3]:
marks = np.array([ 

    [78, 85, 90, 88, 76], 

    [56, 65, 70, 72, 60], 

    [91, 95, 89, 97, 93], 

    [45, 50, 40, 55, 48], 

    [68, 72, 75, 70, 69], 

    [88, 90, 92, 91, 89], 

    [35, 42, 38, 40, 45], 

    [80, 78, 82, 85, 79] 

]) 

In [4]:
print(marks)

[[78 85 90 88 76]
 [56 65 70 72 60]
 [91 95 89 97 93]
 [45 50 40 55 48]
 [68 72 75 70 69]
 [88 90 92 91 89]
 [35 42 38 40 45]
 [80 78 82 85 79]]


In [5]:
print("Shape :", marks.shape)
print("Size :", marks.size)
print("Dimensions :", marks.ndim)
print("Datatype :", marks.dtype)


Shape : (8, 5)
Size : 40
Dimensions : 2
Datatype : int64


In [6]:
total_marks = np.sum(marks, axis=1)
print("\nTotal Marks:")
print(total_marks)


Total Marks:
[417 323 465 238 354 450 200 404]


In [7]:
average_marks = np.mean(marks, axis = 1)
print('\nAverage Marks:')
print(average_marks)


Average Marks:
[83.4 64.6 93.  47.6 70.8 90.  40.  80.8]


In [8]:
subject_average = np.mean(marks, axis=0)
print("\nSubject-wise Average:")
print(subject_average)


Subject-wise Average:
[67.625 72.125 72.    74.75  69.875]


In [9]:
highest_marks = np.max(marks, axis=0)
print("\nHighest Marks:")
print(highest_marks)



Highest Marks:
[91 95 92 97 93]


In [10]:
lowest_marks = np.min(marks, axis=0)
print("\nLowest Marks:")
print(lowest_marks)


Lowest Marks:
[35 42 38 40 45]


In [11]:
print(max(total_marks))

465


In [12]:
top_student = np.argmax(total_marks)

print("\nTop Student Index :", top_student)
print("Total Marks :", total_marks[top_student])


Top Student Index : 2
Total Marks : 465


In [13]:
avg = marks.mean(axis=1)
avg

array([83.4, 64.6, 93. , 47.6, 70.8, 90. , 40. , 80.8])

In [14]:
s = marks[avg>80]
s

array([[78, 85, 90, 88, 76],
       [91, 95, 89, 97, 93],
       [88, 90, 92, 91, 89],
       [80, 78, 82, 85, 79]])

In [15]:
np.any(marks < 40, axis=1)

array([False, False, False, False, False, False,  True, False])

In [16]:
np.where(marks>90)

(array([2, 2, 2, 2, 5, 5]), array([0, 1, 3, 4, 2, 3]))

In [17]:
np.sort(total_marks)[::-1]

array([465, 450, 417, 404, 354, 323, 238, 200])

In [18]:
normalized = (marks - marks.min())/(marks.max()-marks.min())
normalized

array([[0.69354839, 0.80645161, 0.88709677, 0.85483871, 0.66129032],
       [0.33870968, 0.48387097, 0.56451613, 0.59677419, 0.40322581],
       [0.90322581, 0.96774194, 0.87096774, 1.        , 0.93548387],
       [0.16129032, 0.24193548, 0.08064516, 0.32258065, 0.20967742],
       [0.53225806, 0.59677419, 0.64516129, 0.56451613, 0.5483871 ],
       [0.85483871, 0.88709677, 0.91935484, 0.90322581, 0.87096774],
       [0.        , 0.11290323, 0.0483871 , 0.08064516, 0.16129032],
       [0.72580645, 0.69354839, 0.75806452, 0.80645161, 0.70967742]])

In [19]:
salary = np.array([ 

    [45000, 48000, 51000, 54000], 

    [60000, 65000, 70000, 76000], 

    [35000, 36000, 39000, 42000], 

    [90000, 95000,100000,105000], 

    [50000, 52000, 54000, 57000] 

])

In [20]:
yearly_avg_sal = np.mean(salary,axis=0)
yearly_avg_sal

array([56000., 59200., 62800., 66800.])

In [21]:
empl_avg_sal = np.mean(salary,axis=1)
empl_avg_sal

array([49500., 67750., 38000., 97500., 53250.])

In [22]:
growth = salary[:,3]-salary[:,0]
growth

array([ 9000, 16000,  7000, 15000,  7000])

In [23]:
growth_pct = (growth / salary[:, 0]) * 100
growth_pct

array([20.        , 26.66666667, 20.        , 16.66666667, 14.        ])

In [24]:
emp_max = np.argmax(growth)
emp_max

np.int64(1)

In [25]:
emp_min = np.argmin(growth)
emp_min

np.int64(2)

In [26]:
np.sort(growth_pct)

array([14.        , 16.66666667, 20.        , 20.        , 26.66666667])

In [27]:
np.where(growth_pct>20)

(array([1]),)

In [28]:
new_salary = salary * 1.10
new_salary

array([[ 49500.,  52800.,  56100.,  59400.],
       [ 66000.,  71500.,  77000.,  83600.],
       [ 38500.,  39600.,  42900.,  46200.],
       [ 99000., 104500., 110000., 115500.],
       [ 55000.,  57200.,  59400.,  62700.]])

In [29]:
salary.max()

np.int64(105000)

In [30]:
salary.min()

np.int64(35000)

In [31]:
A = np.arange(1,17).reshape(4,4) 

B = np.arange(17,33).reshape(4,4)

In [32]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
B

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [34]:
A+B

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [35]:
A-B

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [36]:
A*B

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [37]:
A@B

array([[ 250,  260,  270,  280],
       [ 618,  644,  670,  696],
       [ 986, 1028, 1070, 1112],
       [1354, 1412, 1470, 1528]])

In [38]:
A.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [39]:
B.T

array([[17, 21, 25, 29],
       [18, 22, 26, 30],
       [19, 23, 27, 31],
       [20, 24, 28, 32]])

In [40]:
np.linalg.det(A)

np.float64(4.7331654313261276e-30)

In [41]:
np.linalg.det(B)

np.float64(2.508577678602836e-28)

In [42]:
np.linalg.inv(A)

array([[ 3.94064967e+15, -4.50359963e+15, -2.81474977e+15,
         3.37769972e+15],
       [-4.12829966e+15,  4.50359963e+15,  3.37769972e+15,
        -3.75299969e+15],
       [-3.56534971e+15,  4.50359963e+15,  1.68884986e+15,
        -2.62709978e+15],
       [ 3.75299969e+15, -4.50359963e+15, -2.25179981e+15,
         3.00239975e+15]])

In [43]:
np.linalg.inv(B)

array([[ 5.66490519e+13,  5.57639105e+13, -2.81474977e+14,
         1.69062014e+14],
       [ 5.66490519e+13, -2.25711066e+14,  2.81474977e+14,
        -1.12412962e+14],
       [-2.83245260e+14,  2.84130401e+14,  2.81474977e+14,
        -2.82360118e+14],
       [ 1.69947156e+14, -1.14183245e+14, -2.81474977e+14,
         2.25711066e+14]])

In [44]:
np.diag(A)

array([ 1,  6, 11, 16])

In [45]:
np.diag(B)

array([17, 22, 27, 32])

In [46]:
np.triu(A)


array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [47]:
np.triu(B)

array([[17, 18, 19, 20],
       [ 0, 22, 23, 24],
       [ 0,  0, 27, 28],
       [ 0,  0,  0, 32]])

In [48]:
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [49]:
np.tril(B)

array([[17,  0,  0,  0],
       [21, 22,  0,  0],
       [25, 26, 27,  0],
       [29, 30, 31, 32]])

In [50]:
A.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [51]:
A.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [52]:

B.flatten()


array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [53]:
B.ravel()

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [54]:
sales = np.array([ 

    [120,150,180,210], 

    [200,220,250,300], 

    [300,350,400,450], 

    [180,210,240,260], 

    [400,450,500,550] 

]) 

In [56]:
quart_t = np.sum(sales,axis=0)
quart_t

array([1200, 1380, 1570, 1770])

In [58]:
quart_avg = sales.mean(axis=0)
quart_avg

array([240., 276., 314., 354.])

In [60]:
sales_p = sales.sum(axis=1)
sales_p

array([ 660,  970, 1500,  890, 1900])

In [62]:
sales_avg = sales.mean(axis=1)
sales_avg

array([165. , 242.5, 375. , 222.5, 475. ])

In [65]:
best_quart = np.argmax(quart_t)
best_quart

np.int64(3)

In [68]:
best_sales = np.argmax(sales_p)
best_sales

np.int64(4)

In [73]:
growth = np.diff(sales,axis=1)
growth

array([[30, 30, 30],
       [20, 30, 50],
       [50, 50, 50],
       [30, 30, 20],
       [50, 50, 50]])

In [75]:
increased_every_quarter = np.all(growth > 0, axis=1)
sales[increased_every_quarter]

array([[120, 150, 180, 210],
       [200, 220, 250, 300],
       [300, 350, 400, 450],
       [180, 210, 240, 260],
       [400, 450, 500, 550]])

In [78]:
sal = sales[sales_p>1200]
sal

array([[300, 350, 400, 450],
       [400, 450, 500, 550]])

In [80]:
nor = (sales - sales.min()) / (sales.max()-sales.min())
nor

array([[0.        , 0.06976744, 0.13953488, 0.20930233],
       [0.18604651, 0.23255814, 0.30232558, 0.41860465],
       [0.41860465, 0.53488372, 0.65116279, 0.76744186],
       [0.13953488, 0.20930233, 0.27906977, 0.3255814 ],
       [0.65116279, 0.76744186, 0.88372093, 1.        ]])

In [81]:
arr = np.arange(1,101).reshape(10,10)

In [82]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [92]:
first = arr[0]
first

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
last = arr[-1]
last

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [95]:
mid_4 = arr[3:7]
mid_4

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [105]:
arr[1:-1,-1]

array([20, 30, 40, 50, 60, 70, 80, 90])

In [111]:
border = np.concatenate([arr[0], arr[-1,::-1], arr[1:-1,0], arr[-2:0:-1,0]])
border

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100,  99,  98,
        97,  96,  95,  94,  93,  92,  91,  11,  21,  31,  41,  51,  61,
        71,  81,  81,  71,  61,  51,  41,  31,  21,  11])

In [115]:
rev_row = arr[:,::-1]
rev_row

array([[ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [118]:
rev_col = arr[::-1,:]
rev_col

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [120]:
rev_mat = arr[::-1,::-1]
rev_mat

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [136]:
even_row = arr[1::2]
even_row

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [139]:
odd_row = arr[:,0::2]
odd_row

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [142]:
center = arr[3:7, 3:7]
center

array([[34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67]])

In [148]:
mul_1 = arr[arr%3==0]=-1
mul_1

-1

In [149]:
mul_5 = arr[arr%5==0]=999
mul_5

999

In [151]:
data = np.array([ 

10,20,np.nan,40,500,60,np.nan, 

80,1000,30,np.nan,50,70 

])

In [152]:
data

array([  10.,   20.,   nan,   40.,  500.,   60.,   nan,   80., 1000.,
         30.,   nan,   50.,   70.])

In [156]:
miss = np.count_nonzero(np.isnan(data))
miss

np.int64(3)

In [159]:
miss_val = np.where(np.isnan(data))
miss_val

(array([ 2,  6, 10]),)

In [160]:
out = data[data>100]
out

array([ 500., 1000.])

In [166]:
median = np.nanmedian(data)
data[np.isnan(data)] = median

In [171]:
out_m = data[data>100] = median
data

array([10., 20., 55., 40., 55., 60., 55., 80., 55., 30., 55., 50., 70.])

In [173]:
data.mean()

np.float64(48.84615384615385)

In [174]:
data.std()

np.float64(18.621105287554162)

In [175]:
data.var()

np.float64(346.7455621301775)

In [176]:
data.min()

np.float64(10.0)

In [177]:
data.max()

np.float64(80.0)

In [178]:
prices = np.array([ 

    [100,200,300], 

    [400,500,600], 

    [700,800,900], 

    [1000,1100,1200] 

])

In [181]:
inc = np.array([1.10,1.20,1.30])
r = prices * inc
r

array([[ 110.,  240.,  390.],
       [ 440.,  600.,  780.],
       [ 770.,  960., 1170.],
       [1100., 1320., 1560.]])

In [182]:
a = np.array([100,200,300])
re = prices + a
re

array([[ 200,  400,  600],
       [ 500,  700,  900],
       [ 800, 1000, 1200],
       [1100, 1300, 1500]])

In [185]:
row_add = np.array([1000,2000,3000,4000]).reshape(4,1)
res = prices + row_add
res

array([[1100, 1200, 1300],
       [2400, 2500, 2600],
       [3700, 3800, 3900],
       [5000, 5100, 5200]])

In [186]:
mul = np.array([1,2,3,4]).reshape(4,1)
resu = prices * mul
resu

array([[ 100,  200,  300],
       [ 800, 1000, 1200],
       [2100, 2400, 2700],
       [4000, 4400, 4800]])

In [188]:
discounted = prices * 0.85
discounted

array([[  85.,  170.,  255.],
       [ 340.,  425.,  510.],
       [ 595.,  680.,  765.],
       [ 850.,  935., 1020.]])

In [189]:
departments = np.array([ 

"IT","HR","Finance","IT","Sales", 

"Finance","IT","HR","Sales","IT", 

"Finance","HR","IT","Sales" 

]) 

In [190]:
departments

array(['IT', 'HR', 'Finance', 'IT', 'Sales', 'Finance', 'IT', 'HR',
       'Sales', 'IT', 'Finance', 'HR', 'IT', 'Sales'], dtype='<U7')

In [193]:
uni = np.unique(departments)
uni

array(['Finance', 'HR', 'IT', 'Sales'], dtype='<U7')

In [194]:
len(uni)

4

In [199]:
unique, count = np.unique(departments, return_counts=True)
print(unique)
print(count)

['Finance' 'HR' 'IT' 'Sales']
[3 3 5 3]


In [202]:
index = np.argmax(count)
unique[index]

np.str_('IT')

In [203]:
index = np.argmin(count)
unique[index]

np.str_('Finance')

In [204]:
np.sort(departments)

array(['Finance', 'Finance', 'Finance', 'HR', 'HR', 'HR', 'IT', 'IT',
       'IT', 'IT', 'IT', 'Sales', 'Sales', 'Sales'], dtype='<U7')

In [205]:
np.where(departments == 'IT')

(array([ 0,  3,  6,  9, 12]),)

In [206]:
a = np.arange(1,13).reshape(3,4) 

b = np.arange(13,25).reshape(3,4) 

In [207]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [208]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [210]:
v = np.vstack((a,b))
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [211]:
h = np.hstack((a,b))
h

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [215]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [216]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [223]:
s0 = np.stack((a,b),axis=0)

In [224]:
s1 = np.stack((a,b),axis = 1)

In [226]:
s2 = np.stack((a,b),axis=2)

In [228]:
parts = np.split(s0, 2, axis=0)
parts

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]),
 array([[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])]

In [229]:
c1 = np.concatenate((a,b), axis=1)
np.split(c1, 4, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]]),
 array([[13, 14],
        [17, 18],
        [21, 22]]),
 array([[15, 16],
        [19, 20],
        [23, 24]])]

In [230]:
arr = np.arange(1, 13)

np.split(arr, [3, 7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11, 12])]